### ISSUE TITLE
Good to see!

### ISSUE THREAD

**Issue by mikhael28** [derekpyoung/derekpyoung.github.io#1]
Happy to see you are continuing your journey! Let me know if there is something I can help you out with - Misha

When the weather get's a bit better, let's get a game of par 3 in.

**Comment by derekpyoung** [comment]
hey! thanks man! yea i started a bootcamp to make the final push to fill in some gaps. going to be locked down into the beginning of spring but we will have to spend some time on the course when its dry! I’m not sure i even remember how to swing its been too long!

**Comment by mikhael28** [comment]
Get it! Looking forward to seeing what you build.
